services:
  backtester:
    container_name: backtester
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    volumes:
      - ./backtester/:/app/backtester/
      - ./main.py:/app/main.py
    restart: unless-stopped
